defaults:
  - data: cvrp50
  - model: paper
  - diffusion: categorical
  - training: default
  - inference: default

data_path: ./data/cvrp50-50_128000_pyvrp.txt

wandb:
  project: difusco-cvrp
  mode: online
  run_name: null
