defaults:
  - data: tsp50
  - model: small
  - diffusion: categorical
  - training: default
  - inference: default

wandb:
  project: difusco-tsp
  mode: online
  run_name: null

data_path: ./data/tsp50_128000_concorde.txt
checkpoint_dir: ./checkpoints
